const apiVersions = require("./docs/generated/api/versions.json");
const { versionSelector, versionCrumb } = require("docusaurus-plugin-openapi-docs/lib/sidebars/utils");

// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  userSidebar: [
    {
      type: 'category',
      label: 'User Manual',
      items: [
        {
          type: 'autogenerated',
          dirName: 'user'
        }
      ]
    },
  ],
  
  developerSidebar: [
    {
      type: 'category',
      label: 'Developer',
      items: [
        {
          type: 'autogenerated',
          dirName: 'developer'
        }
      ]
    },
    {
      type: 'category',
      label: 'Community',
      items: [
        {
          type: 'autogenerated',
          dirName: 'community'
        }
      ]
    },
    {
      type: "html",
      defaultStyle: true,
      value: versionSelector(apiVersions),
      className: "version-button",
    },
    {
      type: "html",
      defaultStyle: true,
      value: versionCrumb("v2.97"),
    },
    {
      type: "category",
      label: "API",
      link: {
        type: "generated-index",
        title: "QAT API (2.97)",
        slug: "api"
      },
      items: require("./docs/generated/api/sidebar.ts").default,
    },
  ],

  productSidebar: [
    {
      type: 'category',
      label: 'ABOUT',
      items: [
        {
          type: 'autogenerated',
          dirName: 'product'
        }
      ]
    },
  ],

  // Previous API version sidebar
  "api-2.12": [
    {
      type: "html",
      defaultStyle: true,
      value: versionSelector(apiVersions),
      className: "version-button",
    },
    {
      type: "html",
      defaultStyle: true,
      value: versionCrumb("v2.12"),
    },
    {
      type: "category",
      label: "API",
      link: {
        type: "generated-index",
        title: "QAT API (2.12)",
        slug: "api-2.12"
      },
      items: require("./docs/generated/api/v2.12/sidebar.ts").default,
    },
  ]
};

export default sidebars;
