backend:
  name: github
  repo: timler/fasp-documentation
  branch: main
  auth_endpoint: https://github.com/login/oauth/authorize
  base_url: https://timler.github.io/fasp-documentation/admin

# Media files configuration
media_folder: "static/img"
public_folder: "/img"

collections:
  # User Documentation
  - name: "user-docs"
    label: "User Documentation"
    folder: "docs/user"
    create: true
    slug: "{{slug}}"
    preview_path: "docs/user/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sidebar Label", name: "sidebar_label", widget: "string"}
      - {label: "Position", name: "sidebar_position", widget: "number"}
      - {label: "Content", name: "body", widget: "markdown"}

  # Developer Documentation
  - name: "developer-docs"
    label: "Developer Documentation"
    folder: "docs/developer"
    create: true
    slug: "{{slug}}"
    preview_path: "docs/developer/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sidebar Label", name: "sidebar_label", widget: "string"}
      - {label: "Position", name: "sidebar_position", widget: "number"}
      - {label: "Content", name: "body", widget: "markdown"}

  # Implementer Documentation
  - name: "implementer-docs"
    label: "Implementer Documentation"
    folder: "docs/implementer"
    create: true
    slug: "{{slug}}"
    preview_path: "docs/implementer/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sidebar Label", name: "sidebar_label", widget: "string"}
      - {label: "Position", name: "sidebar_position", widget: "number"}
      - {label: "Content", name: "body", widget: "markdown"}

  # Community Documentation
  - name: "community-docs"
    label: "Community Documentation"
    folder: "docs/community"
    create: true
    slug: "{{slug}}"
    preview_path: "docs/community/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sidebar Label", name: "sidebar_label", widget: "string"}
      - {label: "Position", name: "sidebar_position", widget: "number"}
      - {label: "Content", name: "body", widget: "markdown"}

  # Product Documentation
  - name: "product-docs"
    label: "Product Documentation"
    folder: "docs/product"
    create: true
    slug: "{{slug}}"
    preview_path: "docs/product/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sidebar Label", name: "sidebar_label", widget: "string"}
      - {label: "Position", name: "sidebar_position", widget: "number"}
      - {label: "Content", name: "body", widget: "markdown"}