const apiVersions = require("./docs/api/versions.json");
const { versionSelector, versionCrumb } = require("docusaurus-plugin-openapi-docs/lib/sidebars/utils");

// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  userSidebar: [
    {
      type: 'category',
      label: 'USER',
      link: {
        type: 'doc',
        id: 'user/intro'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'user'
        }
      ]
    },
  ],
  
  developerSidebar: [
    {
      type: 'category',
      label: 'DEVELOPER',
      link: {
        type: 'doc',
        id: 'developer/intro'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'developer'
        }
      ]
    },
  ],

  implementerSidebar: [
    {
      type: 'category',
      label: 'IMPLEMENTER',
      link: {
        type: 'doc',
        id: 'implementer/intro'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'implementer'
        }
      ]
    },
  ],

  communitySidebar: [
    {
      type: 'category',
      label: 'COMMUNITY',
      link: {
        type: 'doc',
        id: 'community/intro'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'community'
        }
      ]
    },
  ],

  productSidebar: [
    {
      type: 'category',
      label: 'ABOUT',
      link: {
        type: 'doc',
        id: 'product/intro'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'product'
        }
      ]
    },
  ],

  "api-1.0.1": [ // Current version sidebar
    {
      type: "html",
      defaultStyle: true,
      value: versionSelector(apiVersions),
      className: "version-button",
    },
    {
      type: "html",
      defaultStyle: true,
      value: versionCrumb("v1.0.1"),
    },
    {
      type: "category",
      label: "API",
      link: {
        type: "generated-index",
        title: "QAT API (latest)",
      },
      items: require("./docs/api/sidebar.ts"),
    },
  ],

  "api-1.0.0": [ // Previous version sidebar
    {
      type: "html",
      defaultStyle: true,
      value: versionSelector(apiVersions),
      className: "version-button",
    },
    {
      type: "html",
      defaultStyle: true,
      value: versionCrumb("v1.0.0"),
    },
    {
      type: "category",
      label: "API",
      link: {
        type: "generated-index",
        title: "QAT API (v1.0.0)",
      },
      items: require("./docs/api/v1.0.0/sidebar.ts"),
    },
  ],
};

export default sidebars;
